files: ["**/*.js"] # No need to put app/assets/ or vendor/assets here
exclude_paths: ["lib/assets/javascripts", "vendor/assets/javascripts"]
options:
  bitwise:    true
  boss:       true
  browser:    true
  camelcase:  false
  curly:      true
  eqeqeq:     true
  eqnull:     true
  esnext:     true
  expr:       true
  immed:      true
  indent:     2
  latedef:    true
  newcap:     true
  noarg:      true
  node:       true
  quotmark:   single
  regexp:     true
  smarttabs:  true
  strict:     true
  sub:        true
  trailing:   true
  undef:      true
  unused:     true
  globals:
    after:        false
    afterEach:    false
    angular:      false
    before:       false
    beforeEach:   false
    browser:      false
    describe:     false
    expect:       false
    inject:       false
    it:           false
    quepidMocks:  false
    spyOn:        false
    testTry:      false
    jQuery:       true
    "$":          true
